# -*- coding: utf-8 -*-
"""group_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZP4J3zLw6Eoqp8OUF5fVzoAeYOgMuXH4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/heart_disease_dataset.csv')

df.head()

print("Dataset Shape:", df.shape)

df.info()

df.describe()

df.isnull().sum()

print(df['heart_disease'].value_counts())

sns.countplot(x='heart_disease', data=df)
plt.title('Heart Disease Distribution')
plt.xlabel('Heart Disease (0 = No, 1 = Yes)')
plt.ylabel('Count')
plt.show()

X = df.drop('heart_disease', axis=1)

y = df['heart_disease']

print("X shape:", X.shape)
print("y shape:", y.shape)

y.value_counts()

y.value_counts(normalize=True) * 100

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(6,4))

sns.countplot(
    x='heart_disease',
    data=df
)

plt.title('Heart Disease Distribution')
plt.xlabel('Heart Disease')
plt.ylabel('Number of Patients')

plt.show()

plt.figure(figsize=(15,8))

sns.boxplot(data=df)

plt.xticks(rotation=90)

plt.title('Boxplot of Dataset Features')

plt.show()

df.skew(numeric_only=True)

plt.figure(figsize=(12,9))

correlation = df.corr()

sns.heatmap(
    correlation,
    annot=True,
    fmt='.2f',
    cmap='coolwarm'
)

plt.title('Correlation Matrix')

plt.show()

df.corr()['heart_disease'].sort_values(ascending=False)

sns.boxplot(
    x='heart_disease',
    y='age',
    data=df
)

plt.title('Age vs Heart Disease')
plt.show()

sns.boxplot(
    x='heart_disease',
    y='max_heart_rate',
    data=df
)

plt.title('Maximum Heart Rate vs Heart Disease')
plt.show()

sns.boxplot(
    x='heart_disease',
    y='cholesterol',
    data=df
)

plt.title('Cholesterol vs Heart Disease')
plt.show()

sns.boxplot(
    x='heart_disease',
    y='resting_blood_pressure',
    data=df
)

plt.title('Resting Blood Pressure vs Heart Disease')
plt.show()

sns.boxplot(
    x='heart_disease',
    y='st_depression',
    data=df
)

plt.title('ST Depression vs Heart Disease')
plt.show()

from sklearn.model_selection import train_test_split

X = df.drop('heart_disease', axis=1)
y = df['heart_disease']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

lr_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression(random_state=42))
])

from sklearn.svm import SVC

svm_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', SVC(
        probability=True,
        random_state=42
    ))
])

from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(
    random_state=42
)

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    random_state=42
)

lr_model = Pipeline([
    ('scaler', StandardScaler()),
    ('classifier', LogisticRegression(
        random_state=42,
        max_iter=1000
    ))
])

lr_model.fit(X_train, y_train)

y_pred_lr = lr_model.predict(X_test)

y_prob_lr = lr_model.predict_proba(X_test)[:, 1]

dt_model.fit(X_train, y_train)

y_pred_dt = dt_model.predict(X_test)

y_prob_dt = dt_model.predict_proba(X_test)[:, 1]

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

y_prob_rf = rf_model.predict_proba(X_test)[:, 1]

svm_model = Pipeline([
    ('scaler', StandardScaler()),
    ('classifier', SVC(
        probability=True,
        random_state=42
    ))
])

svm_model.fit(X_train, y_train)

y_pred_svm = svm_model.predict(X_test)

y_prob_svm = svm_model.predict_proba(X_test)[:, 1]

def evaluate_model(model_name, y_true, y_pred, y_prob):

    # Confusion Matrix
    cm = confusion_matrix(y_true, y_pred)

    tn, fp, fn, tp = cm.ravel()

    # Metrics
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred)
    recall = recall_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred)
    specificity = tn / (tn + fp)
    roc_auc = roc_auc_score(y_true, y_prob)

    print(f"\n{'='*50}")
    print(model_name)
    print(f"{'='*50}")

    print("Accuracy    :", round(accuracy, 4))
    print("Precision   :", round(precision, 4))
    print("Recall      :", round(recall, 4))
    print("F1-Score    :", round(f1, 4))
    print("Specificity :", round(specificity, 4))
    print("ROC-AUC     :", round(roc_auc, 4))

    print("\nConfusion Matrix:")
    print(cm)

    print("\nClassification Report:")
    print(classification_report(y_true, y_pred))

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report,
    roc_curve
)

evaluate_model(
    "Logistic Regression",
    y_test,
    y_pred_lr,
    y_prob_lr
)

evaluate_model(
    "Decision Tree",
    y_test,
    y_pred_dt,
    y_prob_dt
)

evaluate_model(
    "Random Forest",
    y_test,
    y_pred_rf,
    y_prob_rf
)

evaluate_model(
    "SVM",
    y_test,
    y_pred_svm,
    y_prob_svm
)

results = []

models_data = [
    ("Logistic Regression", y_pred_lr, y_prob_lr),
    ("Decision Tree", y_pred_dt, y_prob_dt),
    ("Random Forest", y_pred_rf, y_prob_rf),
    ("SVM", y_pred_svm, y_prob_svm)
]

for name, y_pred, y_prob in models_data:

    cm = confusion_matrix(y_test, y_pred)

    tn, fp, fn, tp = cm.ravel()

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1-Score": f1_score(y_test, y_pred),
        "Specificity": tn / (tn + fp),
        "ROC-AUC": roc_auc_score(y_test, y_prob)
    })

results_df = pd.DataFrame(results)

results_df

results_plot = results_df.set_index('Model')

results_plot.plot(
    kind='bar',
    figsize=(12,6)
)

plt.title('Model Performance Comparison')
plt.ylabel('Score')
plt.xticks(rotation=0)
plt.ylim(0, 1)

plt.legend(
    bbox_to_anchor=(1.02, 1),
    loc='upper left'
)

plt.tight_layout()
plt.show()

plt.figure(figsize=(9,7))

models_roc = [
    ("Logistic Regression", y_prob_lr),
    ("Decision Tree", y_prob_dt),
    ("Random Forest", y_prob_rf),
    ("SVM", y_prob_svm)
]

for name, y_prob in models_roc:

    fpr, tpr, _ = roc_curve(
        y_test,
        y_prob
    )

    auc = roc_auc_score(
        y_test,
        y_prob
    )

    plt.plot(
        fpr,
        tpr,
        label=f"{name} (AUC = {auc:.3f})"
    )

plt.plot(
    [0, 1],
    [0, 1],
    linestyle='--'
)

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')

plt.title('ROC Curve Comparison')

plt.legend()

plt.show()

cm = confusion_matrix(y_test, y_pred_lr)

plt.figure(figsize=(5,4))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.title('Logistic Regression - Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

results_df = pd.DataFrame({
    'Model': [
        'Logistic Regression',
        'Decision Tree',
        'Random Forest',
        'SVM'
    ],
    'Accuracy': [
        0.6750,
        0.5750,
        0.6625,
        0.6500
    ],
    'Precision': [
        0.6957,
        0.6000,
        0.6735,
        0.6739
    ],
    'Recall': [
        0.7273,
        0.6818,
        0.7500,
        0.7045
    ],
    'F1-Score': [
        0.7111,
        0.6383,
        0.7097,
        0.6889
    ],
    'Specificity': [
        0.6111,
        0.4444,
        0.5556,
        0.5833
    ],
    'ROC-AUC': [
        0.7342,
        0.5631,
        0.7601,
        0.7355
    ]
})

results_df

from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.ensemble import RandomForestClassifier

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

rf_model = RandomForestClassifier(
    random_state=42
)

scoring = {
    'accuracy': 'accuracy',
    'precision': 'precision',
    'recall': 'recall',
    'f1': 'f1',
    'roc_auc': 'roc_auc'
}

cv_scores = cross_validate(
    rf_model,
    X_train,
    y_train,
    cv=cv,
    scoring=scoring,
    n_jobs=-1
)

print("5-Fold Cross Validation Results")
print("--------------------------------")

print("Accuracy :", cv_scores['test_accuracy'].mean())
print("Precision:", cv_scores['test_precision'].mean())
print("Recall   :", cv_scores['test_recall'].mean())
print("F1       :", cv_scores['test_f1'].mean())
print("ROC-AUC  :", cv_scores['test_roc_auc'].mean())



from sklearn.model_selection import RandomizedSearchCV

rf = RandomForestClassifier(
    random_state=42
)

param_dist = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [None, 5, 10, 15],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2']
}

random_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_dist,
    n_iter=20,              # only 20 combinations
    scoring='f1',
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

random_search.fit(X_train, y_train)

print("Best Parameters:")
print(random_search.best_params_)

print("\nBest Cross-Validation F1:")
print(random_search.best_score_)

best_rf = random_search.best_estimator_

y_pred_rf_tuned = best_rf.predict(X_test)

y_prob_rf_tuned = best_rf.predict_proba(X_test)[:, 1]

cm = confusion_matrix(
    y_test,
    y_pred_rf_tuned
)

tn, fp, fn, tp = cm.ravel()

accuracy = accuracy_score(
    y_test,
    y_pred_rf_tuned
)

precision = precision_score(
    y_test,
    y_pred_rf_tuned
)

recall = recall_score(
    y_test,
    y_pred_rf_tuned
)

f1 = f1_score(
    y_test,
    y_pred_rf_tuned
)

specificity = tn / (tn + fp)

roc_auc = roc_auc_score(
    y_test,
    y_prob_rf_tuned
)

print("Tuned Random Forest")
print("============================")

print("Accuracy    :", round(accuracy, 4))
print("Precision   :", round(precision, 4))
print("Recall      :", round(recall, 4))
print("F1-Score    :", round(f1, 4))
print("Specificity :", round(specificity, 4))
print("ROC-AUC     :", round(roc_auc, 4))

print("\nConfusion Matrix:")
print(cm)

rf_comparison = pd.DataFrame({
    'Metric': [
        'Accuracy',
        'Precision',
        'Recall',
        'F1-Score',
        'Specificity',
        'ROC-AUC'
    ],

    'Baseline Random Forest': [
        accuracy_score(y_test, y_pred_rf),
        precision_score(y_test, y_pred_rf),
        recall_score(y_test, y_pred_rf),
        f1_score(y_test, y_pred_rf),
        confusion_matrix(y_test, y_pred_rf).ravel()[0] /
        (
            confusion_matrix(y_test, y_pred_rf).ravel()[0] +
            confusion_matrix(y_test, y_pred_rf).ravel()[1]
        ),
        roc_auc_score(y_test, y_prob_rf)
    ],

    'Tuned Random Forest': [
        accuracy,
        precision,
        recall,
        f1,
        specificity,
        roc_auc
    ]
})

rf_comparison

import pandas as pd
import ipywidgets as widgets
from IPython.display import display, clear_output

# ============================================
# INPUT FIELDS
# ============================================

age = widgets.IntText(
    description='Age:',
    value=50
)

sex = widgets.Dropdown(
    options=[0, 1],
    description='Sex:',
    value=1
)

chest_pain_type = widgets.Dropdown(
    options=[0, 1, 2, 3],
    description='Chest Pain:',
    value=0
)

resting_blood_pressure = widgets.IntText(
    description='Resting BP:',
    value=120
)

cholesterol = widgets.IntText(
    description='Cholesterol:',
    value=200
)

fasting_blood_sugar = widgets.Dropdown(
    options=[0, 1],
    description='Fasting BS:',
    value=0
)

resting_ecg = widgets.Dropdown(
    options=[0, 1, 2],
    description='Resting ECG:',
    value=0
)

max_heart_rate = widgets.IntText(
    description='Max Heart Rate:',
    value=150
)

exercise_induced_angina = widgets.Dropdown(
    options=[0, 1],
    description='Exercise Angina:',
    value=0
)

st_depression = widgets.FloatText(
    description='ST Depression:',
    value=1.0
)

st_slope = widgets.Dropdown(
    options=[0, 1, 2],
    description='ST Slope:',
    value=1
)

num_major_vessels = widgets.Dropdown(
    options=[0, 1, 2, 3],
    description='Major Vessels:',
    value=0
)

thalassemia = widgets.Dropdown(
    options=[0, 1, 2, 3],
    description='Thalassemia:',
    value=2
)

# ============================================
# BUTTON
# ============================================

predict_button = widgets.Button(
    description='🔮 Predict',
    button_style='success'
)

output = widgets.Output()

# ============================================
# PREDICTION FUNCTION
# ============================================

def predict_heart_disease(b):

    with output:
        clear_output()

        input_data = pd.DataFrame([{
            'age': age.value,
            'sex': sex.value,
            'chest_pain_type': chest_pain_type.value,
            'resting_blood_pressure': resting_blood_pressure.value,
            'cholesterol': cholesterol.value,
            'fasting_blood_sugar': fasting_blood_sugar.value,
            'resting_ecg': resting_ecg.value,
            'max_heart_rate': max_heart_rate.value,
            'exercise_induced_angina': exercise_induced_angina.value,
            'st_depression': st_depression.value,
            'st_slope': st_slope.value,
            'num_major_vessels': num_major_vessels.value,
            'thalassemia': thalassemia.value
        }])

        prediction = best_rf.predict(input_data)[0]

        probability = best_rf.predict_proba(
            input_data
        )[0][1]

        print("=" * 45)
        print("       ❤️ HEART DISEASE PREDICTION")
        print("=" * 45)

        if prediction == 1:
            print("\n⚠️ Prediction: HEART DISEASE")
        else:
            print("\n✅ Prediction: NO HEART DISEASE")

        print(
            f"\nProbability: {probability:.2%}"
        )

        print("=" * 45)


predict_button.on_click(
    predict_heart_disease
)

# ============================================
# DISPLAY UI
# ============================================

ui = widgets.VBox([
    widgets.HTML(
        "<h2>❤️ Heart Disease Prediction</h2>"
    ),
    age,
    sex,
    chest_pain_type,
    resting_blood_pressure,
    cholesterol,
    fasting_blood_sugar,
    resting_ecg,
    max_heart_rate,
    exercise_induced_angina,
    st_depression,
    st_slope,
    num_major_vessels,
    thalassemia,
    predict_button,
    output
])

display(ui)

